spring:
  application:
    name: api-gateway
  sleuth:
    enabled: true
    sampler:
      probability: 1.0 # trace every request 0.05 = 5% of requests    
  zipkin:
    enabled: true
    base-url: http://192.168.99.100:9411/  
  # I am providing my own custom config in ApiGatewayConfiguration Class  
  #cloud:
    #gateway:
      #discovery:
        #locator:
          #enabled: true
          #lower-case-service-id: true
        
    
server:
  port: 8765
  
# Not Really Necessary  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka       
