spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: file:///C:/Users/Elias/Desktop/in28minutes/git/spring-microservices-v2/git-local-config-repo
  application:
    name: spring-cloud-config-server
    
server:
  port: 8888
  
encrypt:
  key: abcdef    