server:
  port: 8000
  
spring:
  application:
    name: currency-exchange   
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    defer-datasource-initialization: true # If you are Spring Boot >=2.5.0 / 
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  sleuth:
    enabled: true
    sampler:
      probability: 1.0 # trace every request 0.05 = 5% of requests    
  zipkin:
    enabled: true
    base-url: http://192.168.99.100:9411/
           
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address} # localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka          
         
resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5     
        wait-duration: 1s
        enable-exponential-backoff: true
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s # 2 requests each 10 seconds
  bulkhead:
    instances:
      sample-api:
        max-concurrent-calls: 10            
                        
                        